export const columns = [
  "Sno",
  "Franchisee Name",
  "Total Orders",
  "Delivered",
  "Attempted",
  "Pending",
  "Rejected",
];

export const data = [
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    totalOrders: 156,
    delivered: 142,
    attempted: 23,
    pending: 4,
    rejected: 5,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },

  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    totalOrders: 156,
    delivered: 142,
    attempted: 23,
    pending: 4,
    rejected: 5,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    totalOrders: 156,
    delivered: 142,
    attempted: 23,
    pending: 4,
    rejected: 5,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 7,
  },
  {
    sno: "02",
    franchiseeName: "QuickMedic",
    totalOrders: 180,
    delivered: 160,
    attempted: 18,
    pending: 2,
    rejected: 10,
  },
];
export const colors = [
  "#6A7683",
  "#6A7683",
  "#6A7683",
  "#48AE50",
  "#418BD6",
  "#E69C1D",
  "#D14B4B",
];
