export const data = [
  {
    Sno: "01",
    franchisee_name: "MediFast Delivery",
    franchisee_iD: 121433422,
    "Total Orders": 156,
    Delivered: 142,
    Attempted: 23,
    Pending: 4,
    Rejected: 5,
  },
  {
    Sno: "02",
    franchisee_name: "QuickMedic",
    franchisee_iD: 121433422,
    "Total Orders": 180,
    Delivered: 160,
    Attempted: 18,
    Pending: 2,
    Rejected: 7,
  },
  {
    Sno: "03",
    franchisee_name: "QuickMedic",
    franchisee_iD: 121433422,
    "Total Orders": 200,
    Delivered: 180,
    Attempted: 20,
    Pending: 4,
    Rejected: 10,
  },
  {
    Sno: "04",
    franchisee_name: "HealthCourier",
    franchisee_iD: 121433422,
    "Total Orders": 220,
    Delivered: 200,
    Attempted: 25,
    Pending: 5,
    Rejected: 8,
  },
  {
    Sno: "05",
    franchisee_name: "MediExpress",
    franchisee_iD: 121433422,
    "Total Orders": 240,
    Delivered: 220,
    Attempted: 30,
    Pending: 6,
    Rejected: 12,
  },
  {
    Sno: "06",
    franchisee_name: "PharmaSwift",
    franchisee_iD: 121433422,
    "Total Orders": 260,
    Delivered: 240,
    Attempted: 35,
    Pending: 7,
    Rejected: 15,
  },
  {
    Sno: "07",
    franchisee_name: "MediFast Delivery",
    franchisee_iD: 121433422,
    "Total Orders": 280,
    Delivered: 260,
    Attempted: 40,
    Pending: 8,
    Rejected: 18,
  },
  {
    Sno: "08",
    franchisee_name: "QuickMedic",
    franchisee_iD: 121433422,
    "Total Orders": 300,
    Delivered: 280,
    Attempted: 45,
    Pending: 9,
    Rejected: 20,
  },
];

export const processedData = data.map((item) => ({
  ...item,
  FranchiseeDetails: [item.franchisee_name, item.franchisee_iD],
}));

export const columns = [
  { header: "Sno", accessor: "Sno" },
  { header: "Franchisee name", accessor: "FranchiseeDetails" },
  { header: "Total Orders", accessor: "Total Orders" },
  { header: "Delivered", accessor: "Delivered" },
  { header: "Attempted", accessor: "Attempted" },
  { header: "Pending", accessor: "Pending" },
  { header: "Rejected", accessor: "Rejected" },
];

export const colors = [
  "#6A7683",
  "#6A7683",
  "#6A7683",
  "#48AE50",
  "#418BD6",
  "#E69C1D",
  "#D14B4B",
];
