export const columns = [
  "Franchisee ID",
  "Franchisee Name",
  "Company Name",
  "No.of pharmacies",
  "Locationt",
  "Action",
];

export const data = [
  {
    franchisee_iD: "#121433422",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
  {
    franchisee_iD: "#121433423",
    franchiseeName: "MediCare Express",
    company_Name: "Trinity medicare & pharmaceuticals",
    no_of_pharmacies: 24,
    location: "Toronto Medical Deliveries 124 street, Toronto.",
    action: "/image/option_icon.svg",
  },
];
export const colors = ["#6A7683", "#6A7683", "#6A7683", "#6A7683"];
