export const columns = [
  "Sno",
  "Franchisee Name",
  "Transaction id",
  "Date",
  "Amount",
];

export const data = [
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
];
export const colors = ["#6A7683", "#6A7683", "#6A7683", "#6A7683", "#48AE50"];
