export const columns = [
  { header: "Sno", accessor: "sno" },
  { header: "Franchisee Name", accessor: "franchiseeName" },
  { header: "Transaction id", accessor: "transaction_id" },
  { header: "Date", accessor: "date" },
  { header: "Amount", accessor: "amount" },
];

export const data = [
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
  {
    sno: "01",
    franchiseeName: "MediFast Delivery",
    transaction_id: 156,
    date: 142,
    amount: 4,
  },
];
export const colors = ["#6A7683", "#6A7683", "#6A7683", "#6A7683", "#48AE50"];
