export const columns = [
  { header: "Order id", accessor: "order_id" },
  { header: "Order type", accessor: "order_type" },
  { header: "Delivey method", accessor: "delivey_method" },
  { header: "Pharmacy", accessor: "pharmacy" },
  { header: "Delivery location", accessor: "delivery_locationt" },
  { header: "Payment method", accessor: "payment_method" },
  { header: "Date", accessor: "date" },
];

export const data = [
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
  {
    order_id: "#923874292303",
    order_type: "Pickup",
    delivey_method: "Express",
    pharmacy: "Pharmacy name",
    delivery_locationt: "Toronto Medical Deliveries 124 street, Toronto.",
    payment_method: "cash",
    date: "Aug 8, 2024",
  },
];
export const colors = ["#212529"];
export const head_colors = ["#6A7683"];
